version: '3.9'
services:
  app:
    platform: 'linux/amd64'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-production}
        - DATABASE_URL=${DATABASE_URL}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
        - NEXTAUTH_URL=${NEXTAUTH_URL}
        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
        - UPLOADTHING_SECRET=${UPLOADTHING_SECRET}
        - UPLOADTHING_APP_ID=${UPLOADTHING_APP_ID}
        - PAGE_URL=${PAGE_URL}
    working_dir: /app
    container_name: stip-app
    ports:
      - '3000:3000'
    image: stip-prod
    env_file: .env
